### ISSUE TITLE
API endpoint for getting all nonprofits

### ISSUE THREAD

**Issue by cfisher36** [hack4impact-utk/uw-211#24]
**Please make sure that #23 is finished before beginning this story**

### Description
This GET endpoint should provide the information that is necessary to render content on the admin dashboard table. We will probably want to prioritize data such as nonprofit names, form/project status, and emails.

### Technical Considerations
- Refer to the [documentation](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) for more details on building out api route handlers.

**Comment by jacksonmowry** [comment]
How should we keep track of Nonprofit/form status? Are we thinking that there will be a defined set of states that an agency can be in (Onboarding, prospective, good standing, and so on)? If so should can we get a consensus on what states we would like as options.

**Comment by cfisher36** [comment]
> How should we keep track of Nonprofit/form status? Are we thinking that there will be a defined set of states that an agency can be in (Onboarding, prospective, good standing, and so on)? If so should can we get a consensus on what states we would like as options.

We probably want to calculate the status at the endpoint based on a timestamp (in the db) for when the information needs to be updated. This will be a little more involved than we were originally thinking since some agencies have irregular schedules for updates to service details.  For now, it will be safe to just assume yearly updates to information from time of creation.

As far as the status types, we'll probably want "Completed", "Needs Review" for within 2 weeks of expiration, "Expired", and "Awaiting Action" after a reminder email has been sent.

**Comment by jacksonmowry** [comment]
Do we have an established naming convention for API endpoints? If not what would you like for this endpoint.
Where would you like to keep the API documentation? I was thinking we could use the wiki on this repo, but just let me know what you would prefer.

**Comment by cfisher36** [comment]
> Do we have an established naming convention for API endpoints? If not what would you like for this endpoint? Where would you like to keep the API documentation? I was thinking we could use the wiki on this repo, but just let me know what you would prefer.

With API endpoints, just try to keep them simple as a general rule of thumb. For this endpoint, I think it would be good to just name it "agencies".

The wiki would be great and probably more convenient for maintaining API docs. I'll periodically upload the docs to Notion as well.
